### PR TITLE
files: fix check for zero sized files

### LINKED ISSUE #384: files: navigating to a draft with uploaded files shows the Progress column as pending
Package version (if known): v6.0

## Describe the bug
Uploading file to a draft and then refreshing the page shows the file in pending state

## Steps to Reproduce
1. Go to a draft with an uploaded file
2. See that the `Progress` column shows pending even though the file is uploaded.

## Expected behavior

The `Progress` column should show the `100%` label

## Screenshots (if applicable)
Screenshot 2021-09-02 at 15 50 56

### PR DESCRIPTION
**Pull request by zzacharo**
closes #384

### CODE REVIEW

File: src/lib/store.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ const preloadFiles = (files) => {
     entries: _get(_files, 'entries', [])
       .map((file) => {
         let hasSize;
```
Comment (fenekku) [inline src/lib/store.js:24]: minor: more compact and less undefined
```suggestion
        let hasSize = file.size >= 0;
```

**Review by fenekku — APPROVED** [review]
